帰ってきたあひる焼きゲーム

* これなん
あのあひる焼きがmikutterでソーシャルゲームになった！
あひるをひたすら焼こう！
あひるさんに焼くなと言ってもらって、大量に経験値をゲット！ライバルに差をつけろ！
フレンド（フォロイー）と一緒にあひるを焼いて、一緒にランクアップ！

あひるを一番うまく焼けるのは君だ！！！

* インストール方法
  以下のコマンドを実行してください。

#+BEGIN_SRC sh
  $ mkdir -p ~/.mikutter/plugin/; git clone https://github.com/toshia/ahiruyaki.git ~/.mikutter/plugin/ahiruyaki/
#+END_SRC

* [#B] あそびかた
  基本的には、mikutter起動中常にゲームが進行します。
** 初期設定
   まず、設定→アクティビティを開き、「あひる焼き」と「あひる焼き（情報）」という項目を探します。
   「あひる焼き」は、ランクアップなどを報せるアクティビティなので、「タイムラインに表示」をチェックしましょう。
   「あひる焼き（情報）」は、スタミナ残量などを報せるものです。これは「ステータスバーに表示」にoチェックを入れるくらいが丁度いいでしょう。
   このあたりは、プレイスタイルによって適当に調整してください。

** アクション
   プレイヤーはスタミナを消費してアクションを起こすことで、経験値を得ることができます。
*** あひるを焼く
   このゲームの目的は、経験値を溜めてランクを上げることです。
   基本的には、「あひる焼き」とツイートすれば、あひるさんが反応してくれます。反応があれば、あひるさんの反応速度に応じて10 + 反応にかかった秒数×10点 の経験値が入ります。あひるさんの反応が遅いほど得点が入るということです。もちろん、反応がなければ点はありません。

   mikutterコマンドに「あひるを焼く」というコマンドが追加されます。どのツイートに対してでもあひる焼きできますが対象ツイートは何の意味も持ちません。このコマンドはスタミナを10消費します。スタミナが足りない場合はそもそもこのコマンドは出現しません。

*** フレンドのあひる焼きをふぁぼる
   フレンドがあひるさんを焼いたら、スタミナを1消費してそのフレンドを自動的にふぁぼります。この時、固定で1点の経験値が入ります。スタミナが足りない場合は、この動作は行われません。

** 用語
*** スタミナ
   あひるを焼く、あひる焼きをふぁぼるなどのアクションを起こすには「スタミナ」を消費します。
   スタミナは、初期状態では最大10点で、アクションを起こすと減少、5分経過すると1回復、ランクアップすると全回復します。
   スタミナは最大値を超えては回復しません。ちょいちょい使っていきましょう。

*** 経験値
	わかるやろ

*** ランク
	経験値が一定数貯まるとランクアップします。インストール直後のランクは1です。
	このゲームはインストールして適当にあひるを焼いていたらなんかランクが上がってるなーうれしいなーというゲームです。ランクを上げることが目的ですが、そんなにがっつかずにゆるゆるやっていきましょう。
	ランクアップすると最大スタミナが1点上昇します。高ランクになればなるほど、たくさんあひるを焼けるのです。

* イベント
  このゲームはいくつかmikutterイベントを発生させます。これを使った遊びを考えるのもmikutterらしいかもしれません…。
** ahiruyaki_baked
   コマンドによってあひるを焼いた時に発生します。スタミナが足りなかったなど、焼くのに失敗した場合は発生しません。
   また、コマンドを使わずに焼いた場合（手焼き）にも発生しません。

** ahiruyaki_stamina_changed(stamina)
   - stamina ::現在のスタミナ値(Integer)

   スタミナ全回復予定時刻が変更された時に呼ばれます。ランクアップによる回復や、スタミナの消費で発生します。
   時間経過に因る自然回復では発生しません。

** ahiruyaki_stamina_full
   スタミナが全回復した時に呼ばれます。時間経過による自然回復で発生します。
   ランクアップによる回復では発生しません。

** ahiruyaki_rankup(rank)
   - rank :: ランクアップ後のランク(Fixnum)

   ランクが上がった時に発生します。

* ファッキュー
** ランクが10くらい上がった
   最初の頃だけだ

** あひるさんとは？
   ご存知、ないのですか？

** マルチアカウントはどうなってるの？
   全アカウントで諸々共通です

** 初音ミクのフィギュアが増えて困ってます
   俺はね、一つ一番気に入ったフィギュアだけ持ってたら、それで良いと思うんだよ。なのになんでこんなにあるのかな。

** チートし放題じゃん
   うん

** こんなあほなことやってて薄い本の進捗どうなんですか
   最悪焼く

** ガチャはないんですか
   何を引くんだよ600ユーロか？

** あひるさんのエゴサがあひる焼きで埋まったらどうするんですか
   敵を殺した奴だけが生き残る
